### ISSUE TITLE
Wrong lib path for hiprtc

### ISSUE THREAD

**Issue by awehrfritz** [ROCm-Developer-Tools/hipamd#43]
https://github.com/ROCm-Developer-Tools/hipamd/blob/3ec1ccdbbbee7090ba854eddd1dee281973a4498/src/hiprtc/CMakeLists.txt#L47

This should be:
``` cmake
  LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/${CMAKE_INSTALL_LIBDIR}
```

This currently leads to build errors in the Fedora packages which uses `lib64` and not `lib`.

@raramakr this seems like an oversight when you updated HIP to use GNUInstallDirs in https://github.com/ROCm-Developer-Tools/hipamd/commit/c92a12faf39210e24d329cc2c7e94dd124e69fed.

**Comment by raramakr** [comment]
Thanks @awehrfritz  for reporting the issue. Can you please share the steps tried to reproduce the issue

**Comment by awehrfritz** [comment]
Sure, the rpm spec file I used to build the packages is here: https://github.com/awehrfritz/rocm-hip-rpm/blob/main/rocm-hip.spec

You can see that I applied the upstream GNUInstallDirs in order to set the correct installation directories for a systemwide installation in Fedora. But with those changes, the hiprtc libraries get installed twice, once in /usr/lib64 and once in /usr/lib. This is obviously wrong - also the rpmbuild fails with this. Setting the directory correctly (see https://github.com/awehrfritz/rocm-hip-rpm/blob/main/rocm-hip.spec#L105) fixes the issue.

**Comment by awehrfritz** [comment]
I should maybe note that building hipamd is quite troublesome altogether, and as you can see in the spec file provided above, requires major interventions due to the utterly broken build process of hipamd.

Also, while the fixes in the spec file make the library compile and install correctly, it still leaves several issues since the `hipcc.pl` script is a mess and essentially doesn't work for any other installation location than `/opt/rocm`. This is also the same in the Debian and Gentoo packages, which fix various of those issues as well in local patches. But even with my fixes to `hipcc.pl`, I still get compiler errors since the ROCm compiler support library adds wildly include directories where it shouldn't do it. Assembling the compiler command manually works though, which is why I'm confident that it's just about the ROCm build system.

**Comment by awehrfritz** [comment]
I should also note that @Mystro256 ran also into issues when attempting to update his Fedora rocm-hip package (https://copr.fedorainfracloud.org/coprs/mystro256/rocm-hip/). And while I assembled the spec file above based on @Mystro256 rocm-opencl and rocm-hip packages, I had to do quite some changes to get it compiled.

**Comment by awehrfritz** [comment]
The issue around the include directories in `hipcc.pl` was discussed on a [Debian mailing list](https://lists.debian.org/debian-ai/2022/05/msg00031.html). Here the relevant part:
> The addition of -isystem "$HIP_CLANG_INCLUDE_PATH/.." to HIPCXXFLAGS and HIPCFLAGS needs to be removed from hipcc [1]. Once HIP is installed in /usr, hipcc ends up passing -isystem /usr/include, which breakes the proper order of C and C++ include paths. If I understand correctly, it's unnecessary for hipcc to pass these flags anyway. A patch to remove them will eventually be made upstream.

This is fixed in the Debian packages with this [patch](https://salsa.debian.org/rocm-team/rocm-hipamd/-/blob/master/debian/patches/0007-isystem-removal.patch).

There are more issues when it comes to installations in locations other than `/opt/rocm`. Here a related bug report regarding the include directories: https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/issues/49

**Comment by raramakr** [comment]
Thank you @awehrfritz . Was able to reproduce the issue - "hiprtc libraries get installed twice"
Fix will be available after internal testing

**Comment by awehrfritz** [comment]
> Thank you @awehrfritz . Was able to reproduce the issue - "hiprtc libraries get installed twice"

Great, thanks for looking into this @raramakr!

Do you want me to report the other issues I mentioned in a separate issue for [HIP](https://github.com/ROCm-Developer-Tools/HIP), or did you have a look at those already as well?

**Comment by raramakr** [comment]
Please report the other issues separately for better tracking

**Comment by awehrfritz** [comment]
@Mystro256: FYI, I will also report the other issues mentioned above in separate bug reports and/or PRs.

**Comment by Mystro256** [comment]
@cgmb as FYI

**Comment by Mystro256** [comment]
I'm just reviewing old issues, this is resolved (another "packaging" cmake was fixed instead), so this can be closed.

**Comment by Mystro256** [comment]
@raramakr do you have close permission? I can confirm the Fedora build is working fine now.
