### ISSUE TITLE
question about boardName

### ISSUE THREAD

**Issue by zjin-lcf** [ROCm-Developer-Tools/hipamd#61]
Do you know where `info.boardName_` in `hipamd/src/hip_device.cpp` is read from ?  The name is empty for some devices (e.g. MI210). Thanks

**Comment by jatinx** [comment]
On linux its HSA_AMD_AGENT_INFO_PRODUCT_NAME of hsa_agent_get_info

**Comment by zjin-lcf** [comment]
Thanks.
