### ISSUE TITLE
Support for setting `hipLimitMallocHeapSize` on ROCm 5.4?

### ISSUE THREAD

**Issue by pxl-th** [ROCm-Developer-Tools/hipamd#70]
On ROCm 5.4 you can [get](https://github.com/ROCm-Developer-Tools/hipamd/blob/474e8620099a463ad2ced821ae7400609b29bf7f/src/hip_device_runtime.cpp#L397) the limit for `hipLimitMallocHeapSize`, but not set it.
But on ROCm 5.5 you can [get](https://github.com/ROCm-Developer-Tools/hipamd/blob/c1741e9b671a58080b7150e11d9130e6a2f22dcb/src/hip_device_runtime.cpp#L404) & [set](https://github.com/ROCm-Developer-Tools/hipamd/blob/c1741e9b671a58080b7150e11d9130e6a2f22dcb/src/hip_device_runtime.cpp#L480) it.
Is it possible to backport setting `hipLimitMallocHeapSize` to ROCm 5.4?

Migrating to ROCm 5.5 currently is not an option due to LLVM 16.

**Comment by jatinx** [comment]
Unfortunately no
